FROM python:3.10-slim

WORKDIR /app

COPY app.py .
COPY vector_service.py .

RUN pip install --no-cache-dir flask sentence-transformers faiss-cpu numpy

EXPOSE 5000
EXPOSE 5005

CMD ["sh", "-c", "python app.py & python vector_service.py && wait"]
